/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import GUI.beans.XGUI_Item;
import javax.swing.JPanel;

/**
 *
 * @author kavan
 */
public class ListItem extends JPanel {

    /**
     * Creates new form ListItemDesign
     */
    // Variables declaration - do not modify
    private javax.swing.JLabel nameLb;
    private javax.swing.JLabel yearLb;
    private String itemName;
    private String itemYear;
    private XGUI_Item item;
    // End of variables declaration

    public ListItem(XGUI_Item bean) {
        this.itemName = bean.getName();
        this.itemYear = bean.getYear();
        this.item = bean;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // 
    private void initComponents() {

        nameLb = new javax.swing.JLabel();
        yearLb = new javax.swing.JLabel();

        nameLb.setFont(new java.awt.Font("Serif", 2, 16)); // NOI18N
        nameLb.setText(this.itemName);

        yearLb.setFont(new java.awt.Font("Serif", 1, 12)); // NOI18N
        yearLb.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        yearLb.setText(this.itemYear);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(nameLb, javax.swing.GroupLayout.PREFERRED_SIZE, 389, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(yearLb, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(19, Short.MAX_VALUE)));
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                .addComponent(yearLb, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(nameLb, javax.swing.GroupLayout.DEFAULT_SIZE, 44, Short.MAX_VALUE))
                .addContainerGap()));
    }// </editor-fold>

    public String getItemName() {
        return itemName;
    }

    public void setItemName(String itemName) {
        this.itemName = itemName;
    }

    public String getItemYear() {
        return itemYear;
    }

    public void setItemYear(String itemYear) {
        this.itemYear = itemYear;
    }

    public XGUI_Item getXGUI_Item() {

        return item;
    }
}
